# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='adders',
            field=models.ManyToManyField(related_name='addedtotable', to='test_app.User'),
        ),
    ]
